AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: aws-apigw-lambda-dynamodb-golang

Parameters:
  ExecutionRole:
    Type: String

Globals:
  Api:
    EndpointConfiguration: REGIONAL
    MethodSettings: [{
                       "ThrottlingRateLimit": 3,
                       "ThrottlingBurstLimit": 5,
                       "MetricsEnabled": True,
                       "DataTraceEnabled": True,
                       # On all Paths & methods
                       "ResourcePath": "/*",
                       "HttpMethod": "*",
                       "LoggingLevel": "INFO"
                     }]

Resources:
  MySkillsDemoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          version: "v1.0.0"
          title: "ServerlessGoDemo"
        schemes:
          - "https"
        consumes:
          - "application/vnd.api+json"
        produces:
          - "application/vnd.api+json"
        paths:
          /test:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                uri:
                  Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DemoLambda.Arn}:live/invocations"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                contentHandling: "CONVERT_TO_TEXT"
                type: "aws_proxy"

  DemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "DemoGoLambda"
      Handler: src/main
      Runtime: go1.x
      Description: 'Go Lambda'
      MemorySize: 128
      Timeout: 3
      Role: !Ref ExecutionRole
      Tracing: Active
      AutoPublishAlias: live
      Events:
        GetRate:
          Type: Api
          Properties:
            Path: /test
            Method: get
            RestApiId:
              Ref: MySkillsDemoApi

